name: Build and Push Kubespray Ansible Builder Image

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Kubespray release version or commit SHA'
        required: true
        type: string

env:
  GROUP: ${{ github.repository_owner }}
  REPO: kubespray-ansible-execution-environment
  KUBESPRAY_REPO: kubernetes-sigs/kubespray

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install ansible-builder
      run: |
        python -m pip install --upgrade pip
        pip install ansible-builder

    - name: Download Kubespray files
      run: |
        mkdir -p kubespray
        cd kubespray
        curl -L https://github.com/${{ env.KUBESPRAY_REPO }}/archive/${{ github.event.inputs.version }}.tar.gz | tar xz --strip-components=1
        cp requirements.txt ../

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push image
      run: |
        ansible-builder build --verbosity 3 -t ghcr.io/${{ env.GROUP }}/${{ env.REPO }}:${{ github.event.inputs.version }} --container-runtime docker
        docker push ghcr.io/${{ env.GROUP }}/${{ env.REPO }}:${{ github.event.inputs.version }}
